sudo: required
language: node_js
services:
- docker
before_install:
- cp .env.example .env
install:
- docker-compose build
script:
- docker-compose run app npm test
notifications:
  slack:
    secure: CB029W2OQ1lpWpTAbSmA0FJn3pvXLBpv0fVKzcP5BerYsB1n0lmI4nPiXj5xmZ1B3f/IaTi2E7IzfAmbkaFbGivjh1ngowuybQyhr5R04nv63o0rE3pchiw8E2EasfVy31vdXXyrW2PKKSLASss3UqC3kIL1fnbC3OIM08WQpf6a2y/baezgdmHjWRUenPr3BDl1fLsqMbRh46OmrGLXEWieG3lktDCy55p0LdqrzcD2luWma2gE60sqsdy/2df1XY8uNIJCr2sV4sTkuBoB5n7todmbFiItTrCgXNWLnecZsvko6vP2s8yTA3eOub4BY4IoFozTuP2kcgUhdC/dMjzwpV5kIoUAoMpc6mZZ6PuW/aUW7urEQBSr1ze6d7RgL76+tZcIPPDEpYw8Nlh/L6L0A8NxV5eJV0FsQltXy/mfewNBkffnXq5uvJKCd8NAM86Uyu33jWCKPK/yRHfiAap4dJM6zHyaRDNYoE1cai3GOvnWoJFL5ceeOcxL98Ohsv94XOEjEeoKYkKdo0fc73lW6fjWuTtqmHxXVW6u9IC52iq6YP8a7DRz70KscUzDDPkxIXXdE4cAYw3VlCGwVBXQ4/rYYQck1ZPXu/wmOIb+xKlhrV64uRtubwVJSykwzOtRUU3KlNeSuoAp9Q8OaafxdybPGTwEcHVmK0xdd9Y=
