version: '2'

services:
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db

  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
  
  nginx:
    image: cmr1/nginx-proxy
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - app

volumes:
  mongo: